// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LinksBug2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void linksBug2() {
    driver.get("https://www.google.com/drive/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.id("glue-carousel-1")).click();
    {
      WebElement element = driver.findElement(By.xpath("//section/div/div/div/div[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//section/div/div/div/div[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//section/div/div/div/div[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//section/div/div/div/div[3]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//section/div/div/div/div[3]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//section/div/div/div/div[3]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("//section/div/div/div/div[3]")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[4]")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[3]")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[2]")).click();
    driver.findElement(By.xpath("//section[6]/section/div/div/div/div")).click();
    driver.findElement(By.xpath("//section[6]/section/div/div/div/div")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[2]")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[2]")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[3]")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[3]")).click();
    driver.findElement(By.xpath("//section/div/div/div/div[4]")).click();
  }
}
