// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Login2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void login2() {
    driver.get("https://www.google.com/intl/ru/drive/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hero-dropdown-cta")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Для личного использования")).click();
    vars.put("win4472", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win4472").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".hero-dropdown-cta")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Для работы или бизнеса")).click();
    vars.put("win6306", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6306").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win4472").toString());
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".KKjvXb > .vRMGwf")).click();
    driver.findElement(By.cssSelector(".OA0qNb > .KKjvXb > .vRMGwf")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".PrDSKc > button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".KKjvXb > .vRMGwf")).click();
    driver.findElement(By.cssSelector(".OA0qNb > .KKjvXb")).click();
    {
      WebElement element = driver.findElement(By.linkText("Конфиденциальность"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Справка")).click();
    vars.put("win7504", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7504").toString());
    driver.switchTo().window(vars.get("win4472").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Конфиденциальность")).click();
    vars.put("win7462", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7462").toString());
    driver.switchTo().window(vars.get("win4472").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Условия")).click();
    vars.put("win1314", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1314").toString());
    driver.switchTo().window(vars.get("win4472").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".H2SoFe")).click();
    driver.findElement(By.id("identifierId")).sendKeys("thisaddresddfdsnvksdfnjkn@gmail.com");
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".H2SoFe")).click();
    driver.findElement(By.cssSelector(".WEQkZc")).click();
    driver.findElement(By.cssSelector(".PrDSKc > button")).click();
    driver.findElement(By.id("recoveryIdentifierId")).sendKeys("+77777777777");
    driver.findElement(By.cssSelector(".VfPpkd-vQzf8d")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-vQzf8d"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.cssSelector(".VfPpkd-RLmnJb")).click();
    driver.findElement(By.cssSelector(".VfPpkd-vQzf8d")).click();
    driver.findElement(By.id("firstName")).sendKeys("11");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("11");
    driver.findElement(By.cssSelector(".VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-RLmnJb")).click();
    driver.findElement(By.cssSelector(".FliLIb > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".FliLIb > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-StrnGf-rymPhb-b9t22c")).click();
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".ksBjEc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".FliLIb > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d > .VfPpkd-StrnGf-rymPhb-b9t22c")).click();
    driver.findElement(By.cssSelector(".KKjvXb > .vRMGwf")).click();
    driver.findElement(By.cssSelector(".OA0qNb > .KKjvXb > .vRMGwf")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".n4P87 .VfPpkd-RLmnJb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".KKjvXb")).click();
    driver.findElement(By.cssSelector(".OA0qNb > .KKjvXb > .vRMGwf")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".FliLIb > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d")).click();
    driver.findElement(By.cssSelector(".FliLIb > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.cssSelector(".FliLIb > .VfPpkd-vQzf8d")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".FliLIb > .VfPpkd-RLmnJb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d > .VfPpkd-StrnGf-rymPhb-b9t22c")).click();
    driver.findElement(By.id("firstName")).sendKeys("Lenkd");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Zennb");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.cssSelector(".N3Hzgf > .LXRPh")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("zhenyalenib");
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("zhenyalenib");
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".VmOpGe"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".H2SoFe")).click();
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.name("Passwd")).click();
    driver.findElement(By.name("Passwd")).sendKeys("12345678");
    driver.findElement(By.name("ConfirmPasswd")).click();
    driver.findElement(By.name("ConfirmPasswd")).sendKeys("123");
    driver.findElement(By.cssSelector(".VfPpkd-muHVFf-bMcfAe")).click();
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("ConfirmPasswd")).sendKeys("12345678");
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("Passwd")).sendKeys("123");
    driver.findElement(By.name("ConfirmPasswd")).click();
    driver.findElement(By.name("ConfirmPasswd")).sendKeys("123");
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".CxRgyd")).click();
    driver.findElement(By.name("Passwd")).sendKeys("y1t2r3e4");
    driver.findElement(By.name("ConfirmPasswd")).click();
    driver.findElement(By.name("ConfirmPasswd")).sendKeys("y1t2r3e4");
    driver.findElement(By.cssSelector(".VfPpkd-muHVFf-bMcfAe")).click();
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.id("phoneNumberId")).click();
    driver.findElement(By.id("phoneNumberId")).sendKeys("9522201929");
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".KKjvXb > .vRMGwf")).click();
    driver.findElement(By.cssSelector(".KKjvXb")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("zhenya");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("gerud");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("zhenyalenib");
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("zhenyalenib");
    driver.findElement(By.name("Passwd")).click();
    driver.findElement(By.name("Passwd")).sendKeys("y1t2r3e4");
    driver.findElement(By.name("ConfirmPasswd")).click();
    driver.findElement(By.name("ConfirmPasswd")).sendKeys("y1t2r3e4");
    driver.findElement(By.cssSelector(".VfPpkd-muHVFf-bMcfAe")).click();
    driver.findElement(By.cssSelector(".VfPpkd-muHVFf-bMcfAe")).click();
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click();
    driver.findElement(By.id("phoneNumberId")).click();
    driver.findElement(By.id("phoneNumberId")).sendKeys("9522201929");
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.id("code")).click();
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d")).click();
    driver.findElement(By.id("phoneNumberId")).click();
    driver.findElement(By.id("phoneNumberId")).sendKeys("9522201929");
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".VfPpkd-fmcmS-yrriRe")).click();
    driver.findElement(By.id("phoneNumberId")).click();
    driver.findElement(By.id("phoneNumberId")).click();
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".KKjvXb")).click();
    driver.findElement(By.cssSelector(".OA0qNb > .KKjvXb")).click();
    driver.findElement(By.cssSelector(".Wxwduf")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("qwe");
    driver.findElement(By.cssSelector(".eEgeR > .hDp5Db:nth-child(2) .OabDMe")).click();
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("rew");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("zhenyalenib");
    driver.findElement(By.name("Passwd")).click();
    driver.findElement(By.name("Passwd")).sendKeys("2we34rt5");
    driver.findElement(By.name("ConfirmPasswd")).click();
    driver.findElement(By.name("ConfirmPasswd")).sendKeys("2we34rt5");
    driver.findElement(By.cssSelector(".VfPpkd-muHVFf-bMcfAe")).click();
    driver.findElement(By.cssSelector(".VfPpkd-muHVFf-bMcfAe")).click();
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click();
    driver.findElement(By.id("phoneNumberId")).click();
    driver.findElement(By.id("phoneNumberId")).sendKeys("9522201929");
    driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
