// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SettingsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void settings() {
    driver.get("https://www.google.com/drive/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[4]/div/a")).click();
    vars.put("win1041", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1041").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".gb_Te"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".gb_Te > path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".h-R-d-W .a-s-fa-Ha-pa")).click();
    driver.findElement(By.xpath("//div/div/div/div[6]/div[2]/div/div")).click();
    driver.findElement(By.xpath("//div[24]/div/div[2]/div")).click();
    driver.findElement(By.xpath("//div[23]/div/div")).click();
    driver.findElement(By.cssSelector("circle:nth-child(2)")).click();
    driver.findElement(By.xpath("//div[2]/div/div[2]/div/div/div/div[6]")).click();
    driver.findElement(By.xpath("//div[6]/div[2]/div/div/div")).click();
    driver.findElement(By.xpath("//div[24]/div/div[3]/div")).click();
    driver.findElement(By.xpath("//div[23]/div/div")).click();
  }
}
