// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WorkingTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void workingTest() {
    driver.get("https://www.google.com/drive/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[4]/div/a")).click();
    vars.put("win9477", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9477").toString());
    driver.findElement(By.xpath("//div[2]/div/div[2]/div/span")).click();
    driver.findElement(By.xpath("//div[3]/div/div[2]/div/span")).click();
    driver.findElement(By.xpath("//div[4]/div/div[2]/div/span")).click();
    driver.findElement(By.xpath("//div[5]/div/div[2]/div/span")).click();
    driver.findElement(By.xpath("//div[6]/div/div[2]/div/span")).click();
    driver.findElement(By.xpath("//div[7]/div/div[2]/div/span")).click();
    driver.findElement(By.xpath("//header[@id=\'gb\']/div[2]/div/div[4]/div/a/span")).click();
    driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/div/div[2]")).click();
    driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/div/div[2]")).click();
    driver.findElement(By.cssSelector("#Layer_1 > path:nth-child(1)")).click();
    driver.findElement(By.id("Layer_1")).click();
    driver.findElement(By.xpath("//div[6]/div[3]")).click();
    driver.findElement(By.cssSelector(".SGysBc")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div/div/div/div/div[2]/div/a")).click();
    vars.put("win9168", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9168").toString());
    driver.close();
    driver.switchTo().window(vars.get("win9477").toString());
    driver.findElement(By.cssSelector(".gb_Te")).click();
    driver.findElement(By.cssSelector(".gb_Te")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[2]/div/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[2]/div/div/div/div/div/div[2]/div/div[2]")).click();
    driver.findElement(By.xpath("//div[2]/div/div/div/div/div/div[2]/div/div[2]")).click();
    driver.findElement(By.xpath("//div[2]/div/div/div/div/div/div[2]/div/div[2]")).click();
    vars.put("window_handles", driver.getWindowHandles());
    [object Object]
    vars.put("win3307", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3307").toString());
  }
}
